<?php
/**
 * HiConversion
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * [http://opensource.org/licenses/MIT]
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @Copyright © 2015 HiConversion, Inc. All rights reserved.
 * @license [http://opensource.org/licenses/MIT] MIT License
 */

$helper = $this->helper('Magento\Braintree\Helper\HicHelper');
?>
<?php if ($helper->isEnabled()) :?>
<script type="text/x-magento-init" id="hiconversion_dynamic">
{
    "*": {
        "Magento_Braintree/js/hic/dynamic": {}
    }
}
</script>
<?php endif; ?>

