<?php
/**
 * HiConversion
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * [http://opensource.org/licenses/MIT]
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @Copyright © 2015 HiConversion, Inc. All rights reserved.
 * @license [http://opensource.org/licenses/MIT] MIT License
 */

$helper = $this->helper('Magento\Braintree\Helper\HicHelper');
?>

<?php if ($helper->isEnabled()) :?>
<?php
$hic_data = $helper->getPageData();
?>

<script id="hiconversion_head_page" type="text/javascript">
     var __hic = __hic || {};
    (function(){
        try {
            <?php if (isset($hic_data)) :?>
            __hic.data = __hic.data || {};
                <?php if (null!==$hic_data->getData('page')) :?>
            __hic.data.page = <?php /* @noEscape */ echo Zend_Json::encode($hic_data->getData('page')); ?>;
                <?php endif; ?>
                <?php if (null!==$hic_data->getData('product')) :?>
            __hic.data.product = <?php /* @noEscape */ echo Zend_Json::encode($hic_data->getData('product')); ?>;
                <?php endif; ?>
            <?php endif; ?>
        } catch (e) {
        }
    })();
</script>
<?php endif; ?>
