<?php
/**
 * @var $block \Magento\Braintree\Block\Credit\Calculator\Listing\Product
 */

$scopeId = 'ppcreditsummary' . $block->getProduct()->getId() . mt_rand();
$priceData = $block->getPriceData();
if (!$priceData) {
    return '';
}
?>
<div data-bind="scope: '<?php echo $scopeId; ?>'"><!-- ko template: getTemplate() --><!-- /ko --></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app":{
                "components": {
                    "<?php echo $scopeId; ?>": {
                        "component": "Magento_Braintree/js/paypal/credit/calculator",
                        "template": "Magento_Braintree/credit/calculator",
                        "displaySummary": true,
                        "merchantName": "<?php echo $block->escapeHtmlAttr($block->getMerchantName()); ?>",
                        "instalments": [
                            {
                                "term": <?php echo $priceData->getTerm() ?>,
                                "monthlyPayment": <?php echo $priceData->getMonthlyPayment(); ?>,
                                "apr": <?php echo $priceData->getInstalmentRate(); ?>,
                                "cost": <?php echo $priceData->getCostOfPurchase(); ?>,
                                "costIncInterest": <?php echo $priceData->getTotalIncInterest(); ?>
                            }
                        ]
                    }
                }
            }
        }
    }
</script>