<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Braintree\Block\Paypal\Button $block
 */


$id = $block->getContainerId() . mt_rand();
$config = [
    'Magento_Braintree/js/paypal/button' => [
        'id' => $id,
        'environment' => $block->getEnvironment(),
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'payeeEmail' => $block->getPayeeEmail(),
        'color' => $block->getButtonColor(),
        'shape' => $block->getButtonShape(),
        'actionSuccess' => $block->getActionSuccess()
    ]
];

$creditId = $block->getContainerId() . "_credit" . mt_rand();
$configCredit = $config;
$configCredit['Magento_Braintree/js/paypal/button']['id'] = $creditId;
$configCredit['Magento_Braintree/js/paypal/button']['offerCredit'] = true;
?>

<div data-mage-init='<?php /* @noEscape */ echo json_encode($config); ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo<?php
     /* @noEscape */ echo $block->getContainerId(); ?>-container">
    <div data-currency="<?php /* @noEscape */ echo $block->getCurrency(); ?>"
         data-locale="<?php /* @noEscape */ echo $block->getLocale(); ?>"
         data-amount="<?php /* @noEscape */ echo $block->getAmount(); ?>"
         id="<?php /* @noEscape */ echo $id; ?>"
         class="action-braintree-paypal-logo"></div>
</div>

<?php if ($block->isCreditActive()) : ?>
    <div data-mage-init='<?php /* @noEscape */ echo json_encode($configCredit); ?>'
         class="paypal checkout paypal-logo braintree-paypal-logo<?php
         /* @noEscape */ echo $block->getContainerId(); ?>-container">
        <div data-currency="<?php /* @noEscape */ echo $block->getCurrency(); ?>"
             data-locale="<?php /* @noEscape */ echo $block->getLocale(); ?>"
             data-amount="<?php /* @noEscape */ echo $block->getAmount(); ?>"
             id="<?php /* @noEscape */ echo $creditId; ?>"
             class="action-braintree-paypal-logo"></div>
    </div>
<?php endif; ?>