<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Braintree\Block\Paypal\Button $block
 */

//$id = $block->isCreditActive() ? $block->getContainerId() . "_credit" . mt_rand() :  $block->getContainerId() . mt_rand();
$id = $block->getContainerId() . mt_rand();
$config = [
    'Magento_Braintree/js/paypal/button' => [
        'id' => $id,
        'environment' => $block->getEnvironment(),
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'payeeEmail' => $block->getPayeeEmail(),
//        'color' => $block->getButtonColor(),
        'label' => 'checkout ',
        'shape' => $block->getButtonShape(),
        'size'  => $block->getButtonSize(),
        //'layout'  => $block->getButtonLayout(),
        //'color'  => $block->getButtonColor(),
        'actionSuccess' => $block->getActionSuccess(),
        'offerCredit' => true
        //'offerCredit' => false
        //'offerCredit' => $block->isCreditActive() == true ? true : false
    ]
];
?>
<div data-mage-init='<?php /* @noEscape */ echo json_encode($config); ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo <?php
     /* @noEscape */ echo $block->getContainerId(); ?>-container">
    <div data-currency="<?php /* @noEscape */ echo $block->getCurrency(); ?>"
         data-locale="<?php /* @noEscape */ echo $block->getLocale(); ?>"
         data-amount="<?php /* @noEscape */ echo $block->getAmount(); ?>"
         id="<?php /* @noEscape */ echo $id; ?>"
         class="action-braintree-paypal-logo"></div>
</div>
