<?php

use Magento\Braintree\Block\Paypal\ProductPage;

/** @var ProductPage $block */
try {
    $paypalId = sprintf('paypal-%s-%d', $block->getContainerId(), random_int(PHP_INT_MIN, PHP_INT_MAX));
    $paypalCreditId = sprintf('paypalcredit-%s-%d', $block->getContainerId(), random_int(PHP_INT_MIN, PHP_INT_MAX));
} catch (Exception $e) {
    /**
     * Exception only thrown if an appropriate source of randomness cannot be found.
     * https://www.php.net/manual/en/function.random-int.php
     */
    $paypalId = sprintf('paypal-%s', $block->getContainerId());
    $paypalCreditId = sprintf('paypalcredit-%s', $block->getContainerId());

}

$config = [
    'Magento_Braintree/js/paypal/product-page' => [
        'id' => $paypalId,
        'environment' => $block->getEnvironment(),
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'payeeEmail' => $block->getPayeeEmail(),
        'actionSuccess' => $block->getActionSuccess(),
        'offerCredit' => false,
        'fundingicons' => true,
        'shape' => $block->getButtonShape(),
        'size' => $block->getButtonSize(),
        'layout' => $block->getButtonLayout(),
        'color' => $block->getButtonColor(),
        'disabledFunding' => $block->getDisabledFunding()
    ]
];
$paypalCreditConfig = [
    'Magento_Braintree/js/paypal/product-page' => [
        'id' => $paypalCreditId,
        'environment' => $block->getEnvironment(),
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'payeeEmail' => $block->getPayeeEmail(),
        'actionSuccess' => $block->getActionSuccess(),
        'offerCredit' => true,
        'shape' => $block->getButtonShape(),
        'size' => $block->getButtonSize(),
        'layout' => $block->getButtonLayout(),
        'color' => 'darkblue',
    ]
];
?>

<div data-mage-init='<?= json_encode($config) ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>

<div data-mage-init='<?= json_encode($paypalCreditConfig) ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalCreditId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>