<?php
/**
 * PayPal SDK
 * @var Magento\Braintree\Block\PayPal\Shopping $block
 */
?>
<script src="https://www.paypal.com/sdk/js?client-id=<?= $block->getClientId() ?>&currency=USD&components=tracker"></script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Braintree/js/paypal/shopping": {
                "user": {
                    "name": "Paul Canning",
                    "email": "paul.canning@gene.co.uk"
                }
            }
        }
    }
</script>