<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var Magento\Braintree\Block\Payment $block */
$code = $block->escapeHtml($block->getCode());
?>
<script>
    //<![CDATA[
    require(
        [
            'Magento_Braintree/js/virtual',
            'jquery',
            'domReady!'
        ], function(Braintree, $) {
            var config = <?php /* @noEscape */ echo $block->getPaymentConfig(); ?>,
                payment;
            payment = new Braintree(config);
        });
    //]]>
</script>
