<?php
/** @var $block \Magento\Braintree\Block\Credit\Calculator\Listing\Product */

$scopeId = 'ppcreditsummary-cart';
?>
<div data-bind="scope: '<?= $block->escapeHtmlAttr($scopeId) ?>'"><!-- ko template: getTemplate() --><!-- /ko --></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app":{
                "components": {
                    "<?= $block->escapeHtmlAttr($scopeId) ?>": {
                        "component": "Magento_Braintree/js/paypal/credit/calculator",
                        "template": "Magento_Braintree/credit/calculator",
                        "displaySummary": false,
                        "displayInterestDetails": true,
                        "endpoint": "<?= $block->escapeUrl($block->getUrl('braintree/paypal/cart')) ?>",
                        "merchantName": "<?= $block->escapeHtmlAttr($block->getMerchantName()) ?>",
                        "instalments": []
                    }
                }
            }
        }
    }
</script>
